[theme]
base = "light"
backgroundColor = "#F0EDE8"
secondaryBackgroundColor = "#E8E4DE"
textColor = "#111827"
font = "sans serif"

[client]
showSidebarNavigation = false

[browser]
gatherUsageStats = false
